### ISSUE TITLE
Fix validation for the search endpoint

### ISSUE THREAD

**Issue by pquentin** [elastic/elasticsearch-specification#3122]
## 🐛 Wrong type

Today, the _search endpoint is our top failing endpoints with 70 request examples passing and 1 response examples failing. We should fix those and keep this endpoint green to avoid further regressions.

**Comment by pquentin** [comment]
We're down to 22 failures!

- [ ] `allow_rerank_failures` - waiting for https://github.com/elastic/elasticsearch/pull/122788
- [ ] `function_score` shortcuts: we [don't support them](https://github.com/elastic/elasticsearch-specification/pull/2852#issuecomment-2383564729), but some YAML tests use them. https://github.com/elastic/elasticsearch/pull/137421
  - // Test file: /test/free/search/610_function_score.yml // Test name: Random (twice)
  - // Test file: /test/free/aggregations/random_sampler.yml // Test name: Test random_sampler aggregation with scored subagg
  - // Test file: /test/free/search/610_function_score.yml // Test name: No field only runs on 9.x
  - // Test file: /test/free/aggregations/time_series.yml // Test name: Score test filter some
  - // Test file: /test/free/aggregations/random_sampler.yml // Test name: Test random_sampler aggregation with scored subagg
- [ ] Hex query_vector: https://github.com/elastic/elasticsearch-specification/pull/5401 (4 tests)
- [ ] Strings in range aggregation: https://github.com/elastic/elasticsearch-specification/pull/5402
- [x] `geo_line` aggregation sort: https://github.com/elastic/elasticsearch-specification/pull/5551
  - // Test file: /test/platinum/spatial/120_position_geo_line.yml // Test name: geo_line on position field no sort field or sort order specified
 - [x] Percentiles aggregation with `percents` set to single number instead of number array: https://github.com/elastic/elasticsearch-specification/pull/5552
   - // Test file: /test/free/aggregations/empty_field_metric.yml // Test name: Basic test
 - [ ] `max_analyzed_offset` set to a string in highlight object
   - // Test file: /test/free/search.highlight/30_max_analyzed_offset.yml
 - [ ] Knn search with _name
   - // Test file: /test/free/search.vectors/40_knn_search.yml
 - [ ] semantic text with `lenient` field
   - // Test file: /test/platinum/inference/40_semantic_text_query.yml // Test name: Query the wrong field type with lenient: true
 - [x] random_reranker: https://github.com/elastic/clients-flight-recorder/pull/1416
 - [ ] `counted_terms` aggregation: // Test file: /test/platinum/counted_keyword/* (3 failures)
